[package]
name = "media_stream_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "1.0.0"
etherparse = "0.13.0"
rtp = "0.6.8"
webrtc-util = "0.7.0"
