[package]
name = "rtpeeker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = [ "full" ] }
warp = "0.3"

# not using workspaces, as the crates use different targets
