[package]
name = "rtpeeker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = [ "full" ] }
warp = "0.3"

[workspace]
members = [ "common" ]
# client outside of the workspace
# because of lack of per-package target selection and profile settings
exclude = [ "client" ]
