name: CI

on: push

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [., ./client, ./common]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --check --manifest-path ${{ matrix.dir }}/Cargo.toml

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: cargo-bins/cargo-binstall@main
      - name: Install libpcap
        run: sudo apt-get install libpcap-dev
      - name: Install trunk
        run: cargo binstall --no-confirm --version ~0.18 trunk
      - name: Compile the client
        working-directory: ./client
        run: trunk build --release
      - name: Install rtpeeker
        run: cargo install --locked --path .

# TODO: add clippy check and tests
