name: CI

on: [push, pull_request]

env:
  DIRS: . ./common ./client

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [".", "./client", "./common"]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check --manifest-path ${{ matrix.dir }}/Cargo.toml
        
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [".", "./client", "./common"]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy
      - run: cargo clippy --manifest-path ${{ matrix.dir }}/Cargo.toml -- -Dwarnings

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [".", "./client", "./common"]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: cargo test --manifest-path ${{ matrix.dir }}/Cargo.toml
