name: CI

on: [push, pull_request]

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dir: [".", "./common", "./client"]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - working-directory: ${{ matrix.dir }}
        run: cargo fmt --check
