name: CI

on: push

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [., ./client, ./common]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check --manifest-path ${{ matrix.dir }}/Cargo.toml

  linting:
    name: Build and linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [., ./client, ./common]
        target: [x86_64-unknown-linux-gnu, wasm32-unknown-unknown]
        exclude:
          - dir: .
            target: wasm32-unknown-unknown
          - dir: ./client
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy
      - run: cargo clippy --manifest-path ${{ matrix.dir }}/Cargo.toml --target ${{ matrix.target }} -- -Dwarnings

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # all tests are run on host target
        dir: [., ./client, ./common]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get install libpcap-dev
      - run: cargo test ${{ matrix.flag }} --manifest-path ${{ matrix.dir }}/Cargo.toml
