name: CI

on: [push, pull_request]

env:
  DIRS: . ./common ./client

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    env:
      CMD: cargo fmt --check --manifest-path
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check backend formatting
        run: $CMD ./Cargo.toml
      - name: Check client formatting
        run: $CMD ./client/Cargo.toml
      - name: Check common formatting
        run: $CMD ./common/Cargo.toml
        
